### ISSUE TITLE
[Bug] Can't use any !map commands

### ISSUE THREAD

**Issue by RyanTheEpicGuy4287** [Croebh/Avrae-Customizations#26]
**What alias/snippet is this for?**
Map Utilities

**Describe the bug**
Using any map commands gives an error stating Uvars must be less than 1000 characters.

**To Reproduce**
1. Start initiative
2. type any command that's part of the map (!map, !move, etc.)
3. See a "Uvars must be shorter than 10000 characters" error

**Expected behavior**
The command to run as normal, or at least pulling up the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/75649915/101423839-ee254780-38c7-11eb-9eb1-8f747585a2f9.png)

**Additional context**
This only seems to happen to me. the rest of the server can still use it no problem

**Comment by RyanTheEpicGuy4287** [comment]
Update:

For unknown reasons the "mapStates" uvar was completely screwed. deleting it fixed the bug

**Comment by Croebh** [comment]
The issue is that your backup uvar was quite long. Unfortunately I don't store them by date or anything currently, so it's hard to trim them down. Easiest solution, as I instructed you in the help channel, and worked, is to delete the uvar and start from scratch. You lose all you back ups but honestly I don't know if anyone even uses them.
